version: "3"
services:
  db:
    image: mariadb:latest
    container_name: database
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=postgres
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    ports:
      - "8088:8080"
